#!/bin/sh
./squeeze
chmod 775 *cgi *.sh
../nmt-scripts/publish `basename "$PWD"` "$@" oversight.cgi *.sh *.css *.cgi *.full *.example images help/*.help \
	logs/.keep tmp/.keep install.sh *.html 
#./bundle.unpak
