#!/bin/sh
./squeeze
chmod 775 *cgi *.sh
../nmt-scripts/build `basename "$PWD"` "$@" oversight.cgi \
	*.sh *.css *.cgi *.full *.example images templates help/*.help \
	logs/.keep tmp/.keep *.html bin
#./bundle.unpak
