#!/bin/sh -e
# usage from folder above

# ./util/build 
# ./util/build -label eg -stable

echo r`sh ./util/svnv oversight 1` > src/verfile

cp src/verfile ./conf/.version

v="`cat src/verfile`"
echo ======= $v ==========

chmod 775 *cgi *.sh # *.awk

label="2.0$@-$v"


prompt() {

    while true ; do
        echo "$@ - continue y/n ?"
        read x
        case "x$x" in
            xY|xy) return 0;;
            xN|xn) return 1;;
        esac
    done

}

prompt "Release label is [$label]"

cd src
make ARCH=100 clean
echo "$label" > verfile
make ARCH=100 TRACE1= all

make ARCH=200 clean 
echo "$label" > verfile
make ARCH=200 TRACE1= all 

cd ..

# create example files from default files
for i in unpak catalog oversight ; do
    cp conf/.$i.cfg.defaults conf/$i.cfg.example
done

../nmt-scripts/build `basename "$PWD"` "$label" \
    *.sh *.cgi *.html \
    conf/locale \
    conf/domain \
    conf/*.example conf/.*defaults \
    conf/use.wget.wrapper conf/country.txt conf/.version \
    help/*.help \
    templates.new \
    db \
    bin \
    imdb/imdb.sh \
    imdb/download/.keep logs/.keep tmp/.keep cache/.keep

prompt "Do svn commit and tag"

svn commit -m "release $label"

wget -O - "http://code.google.com/feeds/issues/p/oversight/issues/full?max-results=9999" | awk '{ gsub(/></,">\n<",$0); print }' > issue_list.xml

#svn copy https://oversight.googlecode.com/svn/trunk/  "https://oversight.googlecode.com/svn/tags/$label" -m "$label"
#./bundle.unpak
